import {initialNodes,propose,applyChanges,validOrder,restoreProgress} from './model.mjs';
const $=s=>document.querySelector(s), params=new URLSearchParams(location.search), app=$('#app');
if(params.has('embed'))document.body.classList.add('embedded');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={mode:'home',nodes:initialNodes(),selected:[],goal:'三天内在 310P 上跑通 ONNX 模型推理',preference:'practice',generated:false,busy:false,proposal:null,message:'',stage:'concept',progress:0,history:[],saved:false,from:'',agentId:'',log:'',code:'import numpy as np\n\n# 为模型准备 float32 输入\ninput_data = np.ones((1, 3, 224, 224), dtype=np.float32)\nprint(input_data.shape, input_data.dtype)'};
let timer=null, token=0,noticeTimer;
function notice(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#toast').classList.remove('show'),3600);}
function checkpoint(label){state.history.push({label,nodes:structuredClone(state.nodes),time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});}
function stop(){token++;clearTimeout(timer);state.busy=false;state.agentId='';}
function later(fn,delay=900){const current=token;timer=setTimeout(()=>{if(current===token)fn();},delay);}
const action=(name,text,cls='',more='')=>`<button class="${cls}" data-action="${name}" ${more}>${text}</button>`;
function resourceCards(){return `<div class="resource-grid">${[
 ['ONNX','模型部署','从 ONNX 到首个推理结果','理解流程、模型转换与云端首跑。','template'],
 ['Ascend C','算子开发','从一个 Add 算子开始','认识并行计算与算子的验证方式。','operator'],
 ['310P','部署入门','先体验，再配本地环境','使用云端实验，逐步迁移到本地。','cloud']
 ].map(r=>`<article class="resource"><div class="preview"><b>${r[0]}</b><span>${r[1]}</span></div><div class="info"><h3>${r[2]}</h3><p>${r[3]}</p>${action(r[4],'查看并定制','',r[4]==='operator'?'title="本轮演示聚焦 ONNX 场景"':'')}</div></article>`).join('')}</div>`;}
function home(){return `<div class="home enter"><div class="hero"><div><div class="eyebrow">ASCEND LEARNING</div><h1>把想做的事，变成学得会的路径</h1><p>从目标、已有案例或一份资料开始。路径会沿着你的进度一起调整。</p><div class="goal-box"><textarea id="goal" aria-label="学习目标" placeholder="例如：三天内在 310P 上跑通 ONNX 模型推理"></textarea><div class="actions"><span class="tag gray">支持对话生成 · 案例定制</span>${action('start','一起规划路径','primary')}</div></div></div><img src="../../visual-assets/learning-hi-fi/配图@4x.png" alt="学习与实践插画"></div><div class="section-head"><h2>先看一条做得成的路线</h2><span class="muted">参考路线可预览、可调整</span></div>${resourceCards()}<div class="resume"><div><b>上次学到：模型转换与输入规格</b><p class="muted">保留路径、笔记和最近一次运行现场</p></div>${action('resume','继续学习')}</div></div>`;}
function nodeHtml(n,i,compact=false){const protectedNode=n.done||n.locked;
return `<article class="node ${state.selected.includes(n.id)?'selected':''} ${n.done?'done':''} ${state.agentId===n.id?'agent-target':''}" data-node="${n.id}"><div class="node-title">${compact?'':`<input type="checkbox" aria-label="选择节点：${esc(n.title)}" data-select="${n.id}" ${state.selected.includes(n.id)?'checked':''} ${protectedNode||state.busy?'disabled':''}>`}<b ${!compact&&!protectedNode&&!state.busy?'contenteditable="true" role="textbox" aria-label="修改节点标题"':''} data-title="${n.id}">${compact?(n.done?'已完成 · ':`${i+1}. `):''}${esc(n.title)}</b></div><div class="node-meta"><span class="tag ${n.done?'green':'gray'}">${n.done?'已完成':n.type}</span><small>${n.minutes} 分钟${n.optional?' · 可选':''}${n.locked?' · 已锁定':''}</small></div>${!compact?`<div class="node-tools">${action('selectOne','让 AI 改','',`data-id="${n.id}" ${protectedNode||state.busy?'disabled':''}`)}${action('lock',n.locked?'解锁':'锁定','',`data-id="${n.id}" ${n.done||state.busy?'disabled':''}`)}${action('up','上移','',`data-id="${n.id}" ${protectedNode||state.busy?'disabled':''}`)}${action('down','下移','',`data-id="${n.id}" ${protectedNode||state.busy?'disabled':''}`)}<label><input type="number" min="5" max="240" step="5" value="${n.minutes}" data-minutes="${n.id}" aria-label="${esc(n.title)}的学习时长" ${protectedNode||state.busy?'disabled':''}> 分</label></div>`:''}</article>`;}
function pathPanel(compact=false){const minutes=state.nodes.reduce((s,n)=>s+n.minutes,0);return `<aside class="path-panel"><div class="panel-top"><div class="heading"><h3>${compact?'我的学习路径':'一起编辑这条路径'}</h3>${action('history','版本','quiet')}</div><p>${esc(state.goal)}</p><div class="actions"><span class="tag">310P · ONNX</span><span class="tag gray">${state.nodes.length} 节 / ${minutes} 分</span></div></div><div class="path-list">${state.generated?state.nodes.map((n,i)=>nodeHtml(n,i,compact)).join(''):`<div class="placeholder-path"><h3>${state.busy?'正在把目标连成路径':'你的路径将在这里展开'}</h3><p>${state.busy?esc(state.log):'选择参考后，补充学习偏好即可生成。浏览内容仍然留在左侧。'}</p><div class="progress-rail"><i style="width:${state.progress}%"></i></div></div>`}</div><footer>${compact?`${action('editFromLesson','调整学习路径')}`:`<small>${state.agentId?'AI 正在操作高亮节点':state.generated?'点选节点限定范围；标题与时长可直接编辑。':'确认开始学习前，所有生成结果都是草稿。'}</small><div class="actions">${action('undo','撤销','',!state.history.length||state.busy?'disabled':'')}${action('learn','开始学习','primary',!state.generated||state.busy||state.proposal?'disabled':'')}</div>`}</footer></aside>`;}
function diffHtml(){const p=state.proposal;if(!p)return '';return `<div class="diff enter"><div class="context-head"><b>本次修改预览</b><span class="tag">待确认</span></div>${p.changes.map(c=>c.kind==='defer'?`<div class="minus">暂缓：${esc(c.before)}</div>`:c.kind==='replace'?`<div class="minus">原：${esc(c.before)}</div><div class="plus">改为：${esc(c.after)}</div>`:`<div class="plus">新增：${esc(c.after)} · ${c.minutes} 分钟</div>`).join('')}<p>${p.changes.some(c=>c.kind==='defer')?'本轮终点调整为首跑验证，服务化节点保留在历史版本中。':'调整限定在所选范围，后续节点会保留必要的前置关系。'} 已完成与锁定节点保持不变。</p><div class="actions">${action('apply','确认并应用','primary',state.busy?'disabled':'')}${action('cancel','取消','',state.busy?'disabled':'')}</div></div>`;}
function planning(){return `<div class="work enter"><section class="workspace-main"><div class="planning-context"><div class="breadcrumbs">${state.sourceRun?action('sourceRecord','查看原任务记录')+' · ':''}${action('home','学习首页')} / ${state.from?'从当前学习现场调整':'ONNX 推理部署'}</div><div><div class="eyebrow">${state.from?'KEEP YOUR CONTEXT':'CO-CREATE YOUR PATH'}</div><h2>${state.from?'带着当前进度，调整接下来的安排':'从一条参考路线开始，把它变成你的'}</h2></div>${state.from?`<div class="split-banner">来自「${esc(state.from)}」 · 已完成 ${state.nodes.filter(n=>n.done).length} 节 · 调整后回到原学习现场</div>`:`<div class="context-card"><div class="context-head"><h3>已带入的参考</h3><span class="tag green">已关联</span></div><p>ONNX 模型推理部署 · 官方学习路线</p><div class="actions"><span class="tag gray">310P</span><span class="tag gray">先首跑，再服务化</span><span class="tag gray">原有材料可继续查看</span></div></div>`}<div class="choices">${[['practice','边做边理解','先跑通一个小例子，再补原理'],['theory','先理解再动手','增加概念讲解，再进入实践']].map(([id,t,d])=>`<button class="choice ${state.preference===id?'active':''}" data-action="preference" data-id="${id}"><b>${t}</b><small>${d}</small></button>`).join('')}</div></div><div class="chat-area"><div class="chat-messages">${state.message?`<div class="bubble user">${esc(state.message)}</div>`:''}${state.busy?`<div class="agent-status" role="status">${esc(state.log)} ${action('stop','停止','quiet')}</div>`:state.proposal?diffHtml():`<div class="bubble"><b>学习助手</b><p>${state.generated?'可以直接改节点，也可以告诉我你想怎样调整。我会先把涉及的节点和修改内容展示出来。':'已经带入目标和参考。选择一种学习节奏，就可以在右侧生成路径。'}</p></div>`}${state.generated&&!state.busy&&!state.proposal?`<div class="actions">${action('shorten','只有三天，暂缓服务化','quiet')}${action('extra','给转换步骤补一个练习','quiet')}${action('cloudChange','把环境准备改为云端','quiet')}</div>`:''}</div><div class="composer"><div class="scope-line"><span class="tag">范围：${state.selected.length?state.selected.length+' 个所选节点':'全部未完成节点'}</span>${state.selected.length?action('clearScope','清除选择','quiet'):''}</div><textarea id="instruction" aria-label="给 AI 的路径修改指令" placeholder="选中右侧节点后，说说希望怎样调整…" ${state.busy?'disabled':''}></textarea><div class="actions"><small>预设场景交互演示 · 不调用真实 AI</small>${action(state.generated?'propose':'generate',state.generated?'预览修改':'生成学习路径','primary',state.busy||state.proposal?'disabled':'')}</div></div></div></section>${pathPanel()}</div>`;}
function lessonContent(){
 if(state.stage==='concept')return `<div class="lesson-layout"><div class="video-surface"><div><span class="tag">演示课件 · 非真实课程视频</span><h2 style="margin-top:17px">一个模型，如何在昇腾上运行？</h2><p>从框架模型到可运行产物</p></div><div class="model-flow"><b>ONNX 模型</b><span>→</span><b>ATC 转换</b><span>→</span><b>OM 推理</b></div><div><div class="actions">${action('play',state.busy?'暂停讲解':'播放讲解')}<small style="color:#d6d9e4">${state.progress}% · 流程演示</small></div><div class="progress-rail"><i style="width:${state.progress}%"></i></div></div></div><aside class="chapter-list"><h3>对应知识点</h3><p>01 · 模型与目标硬件</p><p>02 · 转换产物与输入规格</p><p>03 · 如何核对推理结果</p><small>讲解、练习和结果沿同一路径连接。</small></aside></div><div class="lesson-note"><h3>${state.progress<50?'理解关键产物':'输入规格需要保持一致'}</h3><p>${state.progress<50?'ONNX 描述模型的计算图；针对目标硬件转换后，再准备输入并检查输出。':'模型输入的名称、维度和数据类型，需要与转换参数及推理输入保持一致。下一步在练习中核对这些字段。'}</p><div class="actions">${action('finishConcept','已理解，继续准备环境','primary')}</div></div>`;
 if(['env','convert','repair','extra'].includes(state.stage)){const n=state.nodes.find(n=>n.id===state.stage);return `<div class="code-layout"><div class="code-step"><span class="tag">跟练</span><h3 style="margin-top:12px">${esc(n?.title||'准备输入')}</h3><p>在右侧检查输入维度和数据类型，再运行本步示例。</p><small>预期输出</small><p><code>(1, 3, 224, 224) float32</code></p><div class="actions">${action('runPractice','运行本步示例','primary',state.busy?'disabled':'')}</div></div><div class="code-editor"><header><span>input_check.py</span><span>可编辑 · 模拟执行</span></header><textarea id="code" aria-label="练习代码">${esc(state.code)}</textarea></div></div>${state.log?`<div class="terminal enter">${esc(state.log)}</div>`:''}${state.log.includes('核对通过')?`<div class="lesson-note"><span class="tag green">本步已完成</span><p>输入准备已经就绪，接下来沿路径进入${state.stage==='env'?'模型转换':'推理验证'}。</p>${action('nextNode','继续下一节点','primary')}</div>`:''}`;}
 if(state.stage==='run')return `<div class="code-editor"><header><span>HiDevLab · 推理运行</span><span>310P / 演示环境</span></header><pre>模型：resnet50.om\n输入：input.bin\n任务：核对首跑输出与参考结果</pre></div><div class="terminal ${state.log.includes('不匹配')?'error':''}">${esc(state.log||'环境已就绪，等待运行。\n本演示不会连接 NPU 或执行真实推理。')}</div><div class="lesson-note"><div class="actions">${action('runOk','模拟成功运行','primary',state.busy?'disabled':'')}${action('runFail','模拟输入不匹配','',state.busy?'disabled':'')}</div></div>${state.log.includes('验证通过')?`<div class="result-row"><div><small>形状</small><b>匹配</b></div><div><small>数据类型</small><b>匹配</b></div><div><small>输出对照</small><b>通过</b></div></div><div class="lesson-note">${action('finish','完成并整理这条路径','primary')}</div>`:''}${state.log.includes('不匹配')?`<div class="lesson-note"><h3>输入规格不一致</h3><p>已保留本次输入与转换配置。可以带着这些证据请 AI 调整。</p>${action('diagnose','带着错误检查并修复','primary')}</div>`:''}`;
 if(state.stage==='diagnose')return `<div class="repair-layout"><div><span class="tag orange">首跑遇到问题</span><h2 style="margin-top:12px">输入规格与模型不匹配</h2><div class="terminal error">模型期待：1 × 3 × 224 × 224\n本次输入：1 × 224 × 224 × 3\n差异：NCHW / NHWC 维度顺序\n\n演示错误 · 非真实运行日志</div><div class="lesson-note"><h3>上下文已经带入</h3><p>当前节点、输入形状、模型转换信息。只处理这次失败涉及的内容。</p></div></div><div><div class="bubble"><b>学习助手</b><p>建议在「运行推理」前补一个输入规格核对练习，保留已经学完的节点。也可以先查看差异再决定。</p></div><div class="diff"><span class="tag">修改范围：当前运行节点之前</span><div class="plus">新增 · 核对 ATC 输入规格并重新转换</div><p>增加 15 分钟；其余路径不变。确认后先进入补充跟练，再回到刚才的运行现场。</p>${action('repairPath','确认补充并继续','primary',state.busy?'disabled':'')}</div></div></div>`;
 if(state.stage==='finish')return `<div class="success"><span class="tag green">本次首跑学习完成 · 演示结果</span><h1 style="margin-top:16px">让这次走通的路径，成为下次的起点</h1><p>保留有效节点、你的调整和核对方法。复制时重新匹配模型与环境，学习记录分别保存。</p><div class="actions">${action('saveBook',state.saved?'已保存到我的路线':'保存为可复用路线','primary',state.saved?'disabled':'')}${action('editFromLesson','继续调整路径')}</div></div>${state.saved?`<div class="saved-book enter"><div class="context-head"><h3>我的 ONNX 首跑路线</h3><span class="tag green">已保存</span></div><label>下次要用的模型<input id="nextModel" value="MobileNetV2" aria-label="下次使用的模型"></label><ol><li>带入路线结构与学习偏好</li><li>重新核对模型输入与 310P 兼容性</li><li>保留原学习记录，建立新的学习实例</li></ol>${action('reuse','用这条路线开始新任务','primary')}</div>`:''}`;
 return `<div class="lesson-note"><h2>扩展：服务化部署</h2><p>当前首跑已经通过。接下来将输入与推理封装为接口，并验证请求与响应。</p>${action('finish','完成本轮学习','primary')}</div>`;
}
function learning(){const n=state.nodes.find(n=>n.id===state.stage);return `<div class="learning enter">${pathPanel(true)}<section class="lesson-main"><div class="lesson-head"><div><small>我的路径 / ${state.nodes.filter(n=>n.done).length} 节已完成</small><h1>${esc(n?.title||({diagnose:'从错误回到可继续的下一步',finish:'整理与复用'}[state.stage])||'继续学习')}</h1></div>${action('editFromLesson','调整接下来的安排')}</div>${lessonContent()}</section></div>`;}
function render(){app.innerHTML=state.mode==='home'?home():state.mode==='planning'?planning():learning();requestAnimationFrame(()=>{const target=app.querySelector('.agent-target')||app.querySelector('.node.selected')||(state.mode==='learning'?app.querySelector(`[data-node="${state.stage}"]`):null);if(target){const list=target.closest('.path-list');if(list)list.scrollTop=Math.max(0,target.offsetTop-list.offsetTop-list.clientHeight/3);}});}
function openPlanning(){stop();state.mode='planning';state.proposal=null;state.message='';render();}
function generate(){if(state.busy)return;state.busy=true;state.message=state.goal;state.log='正在读取目标与参考路线';state.progress=18;render();later(()=>{state.log='正在安排学习与实践节点';state.progress=58;render();later(()=>{state.nodes=initialNodes();if(/云端/.test(state.goal))state.nodes=applyChanges(state.nodes,propose(state.nodes,['env'],'云端'));if(state.preference==='theory')state.nodes[0].minutes=35;state.generated=true;state.busy=false;state.progress=100;state.log='';checkpoint('首次生成');render();notice('路径已生成，可以点选、直接编辑，或开始学习。');},1100);},850);}
function preview(prompt){state.message=prompt;state.proposal=propose(state.nodes,state.selected,prompt);if(!state.proposal.changes.length){state.proposal=null;notice('当前范围没有可执行的修改。演示支持暂缓服务化、改为云端、补充转换练习。');}render();}
function apply(){if(!state.proposal||state.busy)return;const p=structuredClone(state.proposal);checkpoint('AI 修改前');state.busy=true;state.log='正在定位所选节点';state.agentId=p.changes[0].beforeId||p.changes[0].id;render();later(()=>{state.nodes=applyChanges(state.nodes,p);state.log='节点已调整，正在核对前置关系';state.agentId=p.changes[0].id;state.proposal=null;render();later(()=>{state.busy=false;state.selected=[];state.agentId='';state.log='';render();notice('修改已完成，可撤销或开始学习。');},900);},1100);}
function complete(id){const n=state.nodes.find(n=>n.id===id);if(n)n.done=true;}
function nextNode(){complete(state.stage);const n=state.nodes.find(n=>!n.done);state.stage=n?.id||'finish';state.log='';state.progress=0;render();}
function run(kind){if(state.busy)return;if(kind==='fail'){const n=state.nodes.find(n=>n.id==='run');if(n)n.done=false;}const code=$('#code');if(code)state.code=code.value;state.busy=true;state.log='正在准备输入…';render();later(()=>{state.log='输入已读取，正在核对形状与数据类型…';render();later(()=>{state.busy=false;if(kind==='practice')state.log=/float32/.test(state.code)?'(1, 3, 224, 224) float32\n核对通过 · 模拟执行结果':'未找到 float32 声明，请核对右侧代码。\n本轮是规则模拟，不执行任意代码。';if(kind==='ok'){state.log='shape check: passed\ndtype check: passed\noutput comparison: passed\n验证通过 · 模拟输出';complete('run');}if(kind==='fail')state.log='输入不匹配\nexpected: NCHW [1,3,224,224]\nreceived: NHWC [1,224,224,3]\n请检查转换参数与输入准备。';render();},1000);},700);}
function history(){const dialog=$('#historyDialog');$('#historyList').innerHTML=state.history.length?state.history.map((h,i)=>`<div class="history-row"><div><b>${esc(h.label)}</b><small>${h.time} · ${h.nodes.length} 个节点</small></div>${action('restore','恢复此安排','',`data-index="${i}"`)}</div>`).join(''):'还没有历史版本。';dialog.showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,id=b.dataset.id;
if(a==='sourceRecord'){const d=$('#historyDialog');$('#historyList').innerHTML=`<div class="context-card"><h3>${esc(state.sourceRun.goal)}</h3><p>原任务记录 · ${state.sourceRun.nodes.filter(n=>n.done).length} 节已完成</p>${state.sourceRun.nodes.map(n=>`<p>${n.done?'✓':'○'} ${esc(n.title)}</p>`).join('')}</div>`;d.showModal();}
if(a==='home'){stop();state.mode='home';render();}
if(a==='start'){state.goal=$('#goal')?.value.trim()||state.goal;state.from='';openPlanning();}
if(a==='template'||a==='cloud'){state.from='';state.goal=a==='cloud'?'先用云端环境跑通 ONNX 模型推理':'三天内在 310P 上跑通 ONNX 模型推理';openPlanning();}
if(a==='operator')notice('算子路线为入口示意，本轮可操作场景是 ONNX 推理部署。');
if(a==='preference'){state.preference=id;render();if(state.generated)notice('新偏好已记下；现有路径保持不变，可通过指令继续调整。');}
if(a==='generate')generate();
if(a==='propose'){const text=$('#instruction').value.trim();if(!text)return notice('请先写下希望调整的内容。');preview(text);}
if(a==='shorten'){state.selected=['serve'];preview('我只有三天，先暂缓服务化部署。');}
if(a==='extra'){state.selected=['convert'];preview('给模型转换增加一个输入规格练习。');}
if(a==='cloudChange'){state.selected=['env'];preview('把环境准备改为云端体验。');}
if(a==='selectOne'){state.selected=[id];state.proposal=null;render();$('#instruction')?.focus();}
if(a==='clearScope'){state.selected=[];state.proposal=null;render();}
if(a==='lock'){checkpoint('手动锁定前');state.nodes.find(n=>n.id===id).locked=!state.nodes.find(n=>n.id===id).locked;state.selected=state.selected.filter(x=>x!==id);state.proposal=null;render();}
if(a==='up'||a==='down'){const i=state.nodes.findIndex(n=>n.id===id),j=i+(a==='up'?-1:1);if(j<0||j>=state.nodes.length)return;const draft=structuredClone(state.nodes);if(draft[j].done||draft[j].locked)return notice('已完成或锁定节点的位置保持不变。');[draft[i],draft[j]]=[draft[j],draft[i]];if(!validOrder(draft))return notice('这一步依赖前面的学习内容，当前顺序不能直接交换。可请 AI 修改相关安排。');checkpoint('手动排序前');state.nodes=draft;state.proposal=null;render();}
if(a==='apply')apply();
if(a==='cancel'){state.proposal=null;render();}
if(a==='stop'){stop();state.log='';render();notice('已停止；已经应用的节点变更可撤销。');}
if(a==='undo'){const h=state.history.pop();if(h){stop();state.nodes=restoreProgress(h.nodes,state.nodes);state.proposal=null;state.selected=[];render();notice('已撤销最近一次安排调整，学习进度保留。');}}
if(a==='history')history();
if(a==='closeHistory')$('#historyDialog').close();
if(a==='restore'){stop();const h=state.history[Number(b.dataset.index)];const current=structuredClone(state.nodes);state.nodes=restoreProgress(h.nodes,current);state.history.push({label:'恢复前的安排',nodes:current,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});state.proposal=null;state.selected=[];$('#historyDialog').close();render();notice('已恢复安排，已完成的学习记录仍然保留。');}
if(a==='learn'){stop();state.mode='learning';const returnNode=state.nodes.find(n=>n.id===state.returnStage);const canReturn=returnNode&&returnNode.requires.every(id=>state.nodes.some(n=>n.id===id&&n.done));state.stage=canReturn?returnNode.id:state.nodes.find(n=>!n.done)?.id||'finish';state.returnStage=null;state.log=canReturn?state.returnLog||'':'';state.returnLog='';state.from='';render();}
if(a==='resume'){state.generated=true;complete('concept');complete('env');state.mode='learning';state.stage='convert';state.log='';render();}
if(a==='editFromLesson'){state.returnStage=state.stage;state.returnLog=state.log;const n=state.nodes.find(n=>n.id===state.stage);state.from=n?.title||'当前学习现场';openPlanning();}
if(a==='play'){if(state.busy){stop();render();return;}state.busy=true;const tick=()=>{state.progress=Math.min(100,state.progress+20);if(state.progress===100)state.busy=false;render();if(state.busy)later(tick,1000);};later(tick,500);render();}
if(a==='finishConcept'){stop();complete('concept');state.stage='env';state.log='';render();}
if(a==='runPractice')run('practice');
if(a==='nextNode')nextNode();
if(a==='runOk')run('ok');
if(a==='runFail')run('fail');
if(a==='diagnose'){state.stage='diagnose';render();}
if(a==='repairPath'){checkpoint('失败修复前');const p=propose(state.nodes,['run'],'修复输入兼容问题');state.nodes=applyChanges(state.nodes,p);state.stage='repair';state.log='';render();notice('已插入补充跟练，完成后回到运行节点。');}
if(a==='finish'){stop();state.stage='finish';render();}
if(a==='saveBook'){state.saved=true;try{localStorage.setItem('ascend-ploy-route',JSON.stringify({nodes:state.nodes,preference:state.preference}));}catch{}render();}
if(a==='reuse'){state.sourceRun={goal:state.goal,nodes:structuredClone(state.nodes)};try{localStorage.setItem('ascend-ploy-source-run',JSON.stringify(state.sourceRun));}catch{}const model=$('#nextModel').value.trim()||'新模型';state.nodes=state.nodes.map(n=>({...n,done:false}));state.goal=`在 310P 上完成 ${model} 首跑`;state.from='';state.mode='planning';state.selected=[];state.proposal=null;state.message=`用已保存的路线学习 ${model}，重新核对环境与输入规格。`;state.history=[];render();}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-select]')){const id=e.target.dataset.select;state.selected=e.target.checked?[...state.selected,id]:state.selected.filter(x=>x!==id);state.proposal=null;render();}if(e.target.matches('[data-minutes]')){const n=state.nodes.find(n=>n.id===e.target.dataset.minutes);const value=Number(e.target.value);if(value>=5&&value<=240){checkpoint('手动时长修改前');n.minutes=value;state.proposal=null;render();notice('时长已直接更新，没有调用 AI。');}else{e.target.value=n.minutes;notice('请填写 5–240 分钟。');}}});
document.addEventListener('focusout',e=>{if(!e.target.matches('[contenteditable][data-title]'))return;const n=state.nodes.find(n=>n.id===e.target.dataset.title),v=e.target.textContent.trim();if(v&&v!==n.title){checkpoint('手动标题修改前');n.title=v.slice(0,80);state.proposal=null;notice('标题已直接更新，没有调用 AI。');}else e.target.textContent=n.title;});
document.addEventListener('keydown',e=>{if(e.target.matches('[contenteditable]')&&e.key==='Enter'){e.preventDefault();e.target.blur();}});
const scene=params.get('scene');
if(scene&&scene!=='landing'){state.generated=true;state.mode='planning';checkpoint('原始路径');}
if(scene==='edit'){state.returnStage='convert';state.nodes[0].done=true;state.nodes[1].done=true;state.from='转换模型并检查输入规格';state.selected=['serve'];state.message='我只有三天，先暂缓服务化部署。';state.proposal=propose(state.nodes,state.selected,state.message);}
if(scene==='learn'){state.mode='learning';state.stage='concept';}
if(scene==='repair'){state.mode='learning';state.stage='diagnose';state.nodes.slice(0,3).forEach(n=>n.done=true);}
if(scene==='reuse'){state.mode='learning';state.stage='finish';state.saved=true;state.nodes.slice(0,4).forEach(n=>n.done=true);}
render();
let replayTimers=[];
window.addEventListener('message',e=>{
 if(e.origin!==location.origin||!e.data?.ployDemo)return;
 if(e.data.ployDemo==='reset'){location.reload();return;}
 if(e.data.ployDemo==='pause'){replayTimers.forEach(clearTimeout);replayTimers=[];stop();render();return;}
 if(e.data.ployDemo!=='play')return;
 replayTimers.forEach(clearTimeout);replayTimers=[];
 const click=a=>document.querySelector(`[data-action="${a}"]`)?.click();
 const schedule=(ms,fn)=>replayTimers.push(setTimeout(fn,ms));
 if(!scene||scene==='landing'){
  const input=$('#goal');if(input){input.value='三天内在 310P 上跑通 ONNX 模型推理';input.focus();}
  schedule(1500,()=>click('start'));schedule(3000,()=>click('generate'));
 }else if(scene==='coedit'){
  schedule(200,()=>{state.selected=['env'];render();});
  schedule(1300,()=>{const t=$('#instruction');if(t)t.value='把环境准备改为云端体验';});
  schedule(2700,()=>click('propose'));schedule(4700,()=>click('apply'));
 }else if(scene==='edit'){
  schedule(800,()=>click('apply'));schedule(3900,()=>click('undo'));
 }else if(scene==='learn'){
  click('play');schedule(6000,()=>click('finishConcept'));schedule(7600,()=>click('runPractice'));
 }else if(scene==='repair'){
  schedule(1200,()=>click('repairPath'));schedule(3200,()=>click('runPractice'));schedule(5800,()=>click('nextNode'));schedule(7000,()=>click('runOk'));
 }else if(scene==='reuse'){
  schedule(900,()=>click('reuse'));
 }
});
